server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: group-service
          uri: lb://group-service
          predicates:
            - Path=/groups/**

        - id: scheme-service
          uri: lb://scheme-service
          predicates:
            - Path=/schemes/**

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
